#!/bin/bash

# Requirements
# sudo apt install sshfs


. $HOME/Skripte/functions


# ========================================
# Please edit the lines below
sshloginname="username"   
sship=123.456.789.012
serverbackupdir="Documents/Backup"    
backupfolderlist=( "folder1" "folder2" )    # put as many folders in here as you like
# ========================================



backupfolder=$sshloginname@$sship":$serverbackupdir"

mydate=`date -I`

cd ~

thisbackupfolder="$backupfolder$mydate"
#mkdir "$thisbackupfolder"


echo "----------------------------------------------------------------------------------------------"
mountdir="/tmp/mount$mydate"
mkdir "$mountdir"
sshfs -C $sshloginname@$sship: "$mountdir"

ls "$mountdir"
Ask "Mounted correctly?"  "yes" "no" 
if [ "$result" == "no" ]; then  
	exit;
fi


lastbackupfoldershort=`ls -1 --sort=version  "$mountdir/$serverbackupdir/"| tail -1`
echo "last backup folder is $lastbackupfoldershort"


Ask "Is this the first backup? I found: $lastbackupfoldershort as the last backup folder. Correct?" "yes"  "no" 
if [ "$result" == "yes" ]; then  
	echo "great. Continue"
else
	exit;
fi



for folder in "${backupfolderlist[@]}"; do
	bash ~/Skripte/incrementalBackupFromTo -s  -f "$folder" -t "$thisbackupfolder/" -l "../$lastbackupfoldershort" 

	echo "----------------------------------------------------------------------"
	echo "$folder done"
	echo "$folder done,  `date +%F\ %T`" >> "$mountdir/$serverbackupdir/$mydate/log.txt"
done


