#!/bin/bash




. $HOME/Skripte/functions


echo "###########################"
echo "     Use bash"
echo "###########################"




frompath=""
topath=""
linkdest=""
sizeonly=false

while getopts "sf:t:hl:" optname
do
  case "$optname" in
    "s")
      echo "Option $optname is $OPTARG"
      sizeonly=true
      ;;
    "f")
      echo "Option $optname is $OPTARG"
      frompath=$OPTARG
      ;;
    "t")
      echo "Option $optname is $OPTARG"
      topath=$OPTARG
      ;;
    "l")
      echo "Option $optname is $OPTARG"
      linkdest=$OPTARG
      ;;
    "h")
      echo ""
      echo " Help is always welcome"
      echo ""
      echo ""
      echo " -f  Frompath  (is needed!!!)"
      echo " -t  Backup directory"
      echo " -l  Older Backup path (to make hardlinks to), this path is relative to the Backup directory"
      echo " -s  Compare sizes of files only (not timestamps)"
      echo "   Example:"
      echo "             ~/Skripte/incrementalBackupFromTo  -f myfiles/org/ -t backupfiles/secondbackup -l ../firstbackup"
      echo "   Run it without sh!!!"
      
      exit
      ;;
  esac
done

 
 

if [ "$frompath" = "" ] 
then
  echo "No frompath specified"
  exit;
fi

if [ "$topath" = "" ] 
then
  echo "No topath specified"
  exit;
fi

 

if [ -d "$topath" ]; then
  echo "Backup directory exist already! "
  echo "Please provide a new directoy name, for the new backup path!"

	echo "If not correct please exit in the next 10 seconds?"
	sleep 10
fi



mkdir "$topath"


if [ $sizeonly = true ] 
then
	echo "Size file comparison  only"
		
		
        if [ "$linkdest" = "" ] ;        then
            echo "No linkpath specified,  Creating a full backup"
    
            rsync   --size-only   --protect-args -avhz      --exclude=.thumbnails   --exclude=.cache --exclude=.local/share/Trash/ --exclude=.Private   --exclude=.ecryptfs     "$frompath" "$topath"
        else
            rsync   --size-only   --protect-args -avhz      --exclude=.thumbnails   --exclude=.cache --exclude=.local/share/Trash/ --exclude=.Private  --exclude=.ecryptfs    --link-dest="$linkdest"  "$frompath" "$topath"        
        fi

else

        if [ "$linkdest" = "" ] ;        then
            echo "No linkpath specified,  Creating a full backup"
    
            rsync   --protect-args -avhz      --exclude=.thumbnails   --exclude=.cache --exclude=.local/share/Trash/ --exclude=.Private  --exclude=.ecryptfs      "$frompath" "$topath"
        else
            rsync   --protect-args -avhz      --exclude=.thumbnails   --exclude=.cache --exclude=.local/share/Trash/ --exclude=.Private  --exclude=.ecryptfs    --link-dest="$linkdest"  "$frompath" "$topath"        
        fi


fi





